### ISSUE TITLE
 Investigate macos based riscv compile package

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#147] opened 2024-09-27 17:59 UTC
I don't want to launch docker.

**Comment by fwsGonzo** [comment] 2024-09-27 18:29
Are you having trouble with getting Docker to work?

**Comment by fire** [comment] 2024-09-28 01:55
When the docker build breaks it's very difficult.

**Comment by fwsGonzo** [comment] 2024-09-28 06:17
Sounds like we could improve that part then?

**Comment by fwsGonzo** [comment] 2024-09-28 09:03
I'm going to close this as a duplicate of https://github.com/libriscv/godot-sandbox/issues/141

**Closed by fwsGonzo** 2024-09-28 09:03 UTC
